// admin
export const INIT_AGENTS = 'INIT_AGENTS'
export const INIT_GOODS = 'INIT_GOODS'
export const REQUEST_GOODS = 'REQUEST_GOODS'
export const EDIT_GOODS = 'EDIT_GOODS'
export const DELETE_GOODS = 'DELETE_GOODS'
export const DELETE_FROM_APPLICATION = 'DELETE_FROM_APPLICATION'
export const CHANGE_QUANTITY_GOOD = "CHANGE_QUANTITY_GOOD"
// agent
export const ADD_GOODS_TO_CART = 'ADD_GOODS_TO_CART'
export const DEL_FROM_CART = "DEL_FROM_CART"
export const CLEAR_CART = "CLEAR_CART"
export const ADJUST_CART = "ADJUST_CART"
export const INIT_APPLICATIONS = "INIT_APPLICATIONS"
export const GET_CURRENT_USER = "GET_CURRENT_USER"
